language:
    c

install:
    - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
    - xbuild ./Authorize.NET/AuthorizeNET.csproj
    - xbuild ./AuthorizeNETtest/AuthorizeNETtest.csproj
#    tests migrated to nunit
#    - nunit-console ./AuthorizeNETtest/bin/debug/AuthorizeNETtest.dll -exclude Integration,NotWorkingOnMono
    - nunit-console -exclude Integration,NotWorkingOnMono
	